vectordb:
    vdb_name: "trading-bot"
    index_name: "IVF"

embedding_model:
  provider : "Ollama"
  model_name : "llama3.2:1b"

retriever:
  top_k : 3
  score_threshold: 0.4

llm :
  groq:
    provider : "groq"
    model_name : "deepseek-r1-distill-llama-70b"
  ollama:
    provider : "ollama"
    model_name: "llama3.2:1b"

tools:
  tavily:
    max_results: 3